### PR TITLE
Add docblocks for IDE support

### LINKED ISSUE #9: IDE support
I would be nice if we could have some DocBlocks like @property or @method, along the line of https://github.com/fzaninotto/Faker/blob/master/src/Faker/Generator.php#L6-L174

### PR DESCRIPTION
**Pull request by maxmirazh33**
resolve #9

### CODE REVIEW

**Comment by t-kanstantsin** [comment]
up
please merge it

**Comment by pedro-stanaka** [comment]
Please merge this!

**Comment by GrahamCampbell** [comment]
Thanks! 👍 

Sorry I took so long to merge this!

**Comment by GrahamCampbell** [comment]
Actually, this is wrong, and must be reverted.

**Pull request merged**
